# Generated by Django 4.2.11 on 2024-03-19 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_note_related_job_remove_note_user_cust_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('note_created_at', models.DateTimeField(auto_now_add=True)),
                ('note_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('related_customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
