# Generated by Django 4.2.11 on 2024-03-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_created_by_alter_note_related_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_created_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
