# Generated by Django 4.2.11 on 2024-03-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_employee_organization_and_more'),
        ('notes', '0003_rename_note_created_at_note_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Call Back', 'Call Back'), ('Needs Quote', ' Needs Quote'), ('In Progress', 'In Progress'), ('Payment Needed', 'Payment Needed'), ('Paid/Job Complete', 'Paid/Job Complete')], max_length=50, null=True)),
                ('lead', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_lead', to=settings.AUTH_USER_MODEL)),
                ('related_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_customer', to=settings.AUTH_USER_MODEL)),
                ('related_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
    ]
