# Generated by Django 4.2.11 on 2024-03-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_options_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Job Created', 'Job Created'), ('Call Back', 'Call Back'), ('Needs Quote', ' Needs Quote'), ('In Progress', 'In Progress'), ('Payment Needed', 'Payment Needed'), ('Paid/Job Complete', 'Paid/Job Complete')], default='Job Created', max_length=50, null=True),
        ),
    ]
