# Generated by Django 4.2.11 on 2024-03-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_organization_and_more'),
        ('notes', '0005_note_related_job_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='related_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_customer', to='accounts.customer'),
        ),
    ]
