# Generated by Django 4.2.11 on 2024-06-07 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_alter_job_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lead',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_lead', to=settings.AUTH_USER_MODEL),
        ),

    ]
