# Generated by Django 4.2.11 on 2024-06-07 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0008_alter_job_lead_alter_note_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(default='ac0b31fd-3570-4543-ad45-3e575ff7d164', on_delete=django.db.models.deletion.CASCADE, related_name='updated_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
