# Generated by Django 4.2.11 on 2024-06-11 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0009_alter_note_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
