# Generated by Django 4.2.11 on 2024-06-24 13:52
from django.utils.timezone import now
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_note_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=now, auto_now_add=True),
            preserve_default=False,
        ),
    ]
