# Generated by Django 4.2.11 on 2024-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_job_options_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
