# Generated by Django 4.2.11 on 2024-07-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0012_job_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lead_two',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_lead_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
