# Generated by Django 4.2.11 on 2024-06-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_organization_and_more'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewedcustomer',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
