# Generated by Django 4.2.11 on 2024-06-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_recentlyviewedcustomer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentlyviewedcustomer',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
