# Generated by Django 4.2.11 on 2024-03-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='related_job',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user_cust',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
