# Generated by Django 4.2.11 on 2024-06-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_organization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
