# Generated by Django 4.2.11 on 2024-07-01 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_passwordresettoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
