# Generated by Django 4.2.11 on 2024-07-23 19:53

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordreset_delete_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.validators.validate_phone_number]),
        ),
    ]
